zas asfloat.as
zas ltof.as
zas ftol.as
zas finc.as
zas fbcd.as
zas frndint.as
zas frexp.as
zas float.as

c3 -c -v -o -lf printf.c
c3 -c -v -o -lf fprintf.c
c3 -c -v -o -lf sprintf.c
c3 -c -v -o -lf scanf.c
c3 -c -v -o -lf fscanf.c
c3 -c -v -o -lf sscanf.c
c3 -c -v -o -lf atof.c
c3 -c -v -o -lf doprnt.c
c3 -c -v -o -lf doscan.c
c3 -c -v -o -lf fnum.c
c3 -c -v -o -lf tan.c
c3 -c -v -o -lf acos.c
c3 -c -v -o -lf asin.c
c3 -c -v -o -lf atan2.c
c3 -c -v -o -lf atan.c
c3 -c -v -o -lf cos.c
c3 -c -v -o -lf sin.c
c3 -c -v -o -lf sinh.c
c3 -c -v -o -lf cosh.c
c3 -c -v -o -lf tanh.c 
c3 -c -v -o -lf exp.c
c3 -c -v -o -lf log.c
c3 -c -v -o -lf evalpoly.c
c3 -c -v -o -lf sqrt.c
c3 -c -v -o -lf fabs.c
c3 -c -v -o -lf ceil.c
c3 -c -v -o -lf floor.c

libr r libf.lib printf.obj
libr r libf.lib fprintf.obj
libr r libf.lib sprintf.obj
libr r libf.lib scanf.obj
libr r libf.lib fscanf.obj
libr r libf.lib sscanf.obj
libr r libf.lib doprnt.obj
libr r libf.lib doscan.obj
libr r libf.lib atof.obj
libr r libf.lib fnum.obj
libr r libf.lib fbcd.obj
libr r libf.lib tan.obj
libr r libf.lib acos.obj
libr r libf.lib asin.obj
libr r libf.lib atan2.obj
libr r libf.lib atan.obj
libr r libf.lib cos.obj
libr r libf.lib sin.obj
libr r libf.lib sinh.obj
libr r libf.lib cosh.obj
libr r libf.lib tanh.obj
libr r libf.lib exp.obj
libr r libf.lib log.obj 
libr r libf.lib evalpoly.obj
libr r libf.lib sqrt.obj
libr r libf.lib frexp.obj
libr r libf.lib fabs.obj
libr r libf.lib ceil.obj
libr r libf.lib floor.obj
libr r libf.lib finc.obj
libr r libf.lib asfloat.obj
libr r libf.lib frndint.obj
libr r libf.lib ftol.obj
libr r libf.lib ltof.obj
libr r libf.lib float.obj

libr m libf.lib